### ISSUE TITLE
avr8.rkt inverted assoc

### ISSUE THREAD

**Issue by pdu4** [tiagosr/Plasm#1]
the "assoc" function on in the file[ "avr.rkt"](https://github.com/tiagosr/Plasm/blob/master/avr8.rkt) is inverted 
https://github.com/tiagosr/Plasm/blob/96e813c8008a6bbef9811604d0e143ec9b4cc4d8/avr8.rkt#L17-L46
i.e. it should be (assoc obj alist)
but is (assoc alist obj) 

will make a pull request with corrections soon if you want to accept it

**Comment by tiagosr** [comment]
please make a pull request! I honestly didn't test the avr8 instructions at all - I only catalogued the instructions as kind of pseudocode, I was mostly trying to make the z80 and 68k generators work at the time, I'm glad you found this lib interesting enough to try out and report on the issues. If by fixing this and the other issue they start working, that would be really interesting 😅

**Comment by pdu4** [comment]
Well fixing this and  issue  #2 (multiplication) and the >>  functions  #4 makes the avr8 assembler output correct numbers in the list (as far as I can tell), but I have been stumped by the label issue #5. 
I am trying to make a simple assembler for the atmega32u4 to be used in a larger racket project and this assembler has provided some very interesting ideas for me. Thanks
