### ISSUE TITLE
*a in plasm.rkt doing division

### ISSUE THREAD

**Issue by pdu4** [tiagosr/Plasm#2]
in the [plasm.rkt](https://github.com/tiagosr/Plasm/blob/master/plasm.rkt) file, the function *a is  "connected" to  
`(lambda args (foldl (mkop /) (car args) (cdr args)))`
while the /a function is "connected" to 
`(lambda args (foldl (mkop *) 1 args))`
https://github.com/tiagosr/Plasm/blob/96e813c8008a6bbef9811604d0e143ec9b4cc4d8/plasm.rkt#L49-L76
as avr uses 16bit instructions, this causes every instance to crash with " /: division by zero" everytime
 

as I am trying to study the code, I do not know if this is intentional or not, but  I am guessing not

please let me know if you want a pull request for this

**Comment by tiagosr** [comment]
oh, thanks for catching it! yeah, that was definitely an oversight in my part - I haven't tested it as thoroughly as I should have. I didn't really test the immediate / label expressions at all - I was mainly testing the emitters for the z80 and 68k at that time, and only with immediate values at that. you can make a pull request if you like.
